
table 'Financials'
	lineageTag: e4735796-9e7a-433b-8e89-fa3e3ea8436f

	column 'Segment'
		dataType: string
		lineageTag: 6485ca87-69c0-4242-b58f-6c02bc0f87e3
		summarizeBy: none
		sourceColumn: Segment

	column 'Country'
		dataType: string
		lineageTag: 3a9e5472-29f6-4a3e-8fd6-3ab018f4894f
		summarizeBy: none
		sourceColumn: Country

	column 'Product'
		dataType: string
		lineageTag: f10e31e5-30fc-4475-8dfa-92ac1581d36f
		summarizeBy: none
		sourceColumn: Product

	column 'Discount Band'
		dataType: string
		lineageTag: 4e435762-d49a-4b9e-8e90-2066ad6d2ce9
		summarizeBy: none
		sourceColumn: Discount Band

	column 'Units Sold'
		dataType: decimal
		lineageTag: b83522bf-cee8-43f6-8c01-25ed555ad459
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: Units Sold

	column 'Manufacturing Price'
		dataType: decimal
		lineageTag: 9be4d315-d473-474e-a191-13284820f563
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Manufacturing Price

	column 'Sale Price'
		dataType: decimal
		lineageTag: 218e4ff8-ad9c-4dad-aa44-312b102706eb
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Sale Price

	column 'Gross Sales'
		dataType: decimal
		lineageTag: 2c254e0f-62b2-45ed-aeb0-f92d4bb5d8d8
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Gross Sales

	column 'Discounts'
		dataType: decimal
		lineageTag: c201aa8b-4dac-4285-81b3-abf9bd5f3029
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Discounts

	column 'Sales'
		dataType: decimal
		lineageTag: 4506bf02-c673-4f56-9152-e5016aded097
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Sales

	column 'COGS'
		dataType: decimal
		lineageTag: e9ff108d-0932-42aa-91f1-3c5620744aa5
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: COGS

	column 'Profit'
		dataType: decimal
		lineageTag: a0c4a7c7-888f-41fc-8790-d2a28d026c25
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Profit

	column 'Date'
		dataType: dateTime
		lineageTag: 795b938a-b4a7-476b-88c5-f9fa8527bed5
		summarizeBy: none
		sourceColumn: Date

	column 'Month Number'
		dataType: int64
		lineageTag: f7464e4a-b0cc-4121-be79-8d331d37cbf6
		summarizeBy: sum
		sourceColumn: Month Number

	column 'Month Name'
		dataType: string
		lineageTag: 7e0b2533-40ae-4ed0-bab8-256b69f30602
		summarizeBy: none
		sourceColumn: Month Name

	column 'Year'
		dataType: int64
		lineageTag: dc3c3764-dba8-4402-8e79-2128e69f2eb1
		summarizeBy: sum
		sourceColumn: Year

	partition FINANCIALS = m
		mode: import
		source = ```
let
  Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.148.1226.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
  Sheet = Source{[Item="sheet1",Kind="Table"]}[Data],
  Selected = Table.SelectColumns(Sheet, {"Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", "Sales", "COGS", "Profit", "Date", "Month Number", "Month Name", "Year"}, MissingField.UseNull),
  Typed = Table.TransformColumnTypes(Selected, {{"Segment", Text.Type}, {"Country", Text.Type}, {"Product", Text.Type}, {"Discount Band", Text.Type}, {"Units Sold", Number.Type}, {"Manufacturing Price", Number.Type}, {"Sale Price", Number.Type}, {"Gross Sales", Number.Type}, {"Discounts", Number.Type}, {"Sales", Number.Type}, {"COGS", Number.Type}, {"Profit", Number.Type}, {"Date", DateTime.Type}, {"Month Number", Int64.Type}, {"Month Name", Text.Type}, {"Year", Int64.Type}}),
  __clean_headers_1 =
    let
      CleanedColumns = Table.TransformColumnNames(Sheet, Text.Trim)
    in
      CleanedColumns,
  __convert_types_2 =
    let
      // Convert text columns to proper data types
      ConvertedTypes = Table.TransformColumnTypes(CleanedColumns, {
      {"Segment", type text},
      {"Country", type text},
      {"Product", type text},
      {"Discount Band", type text},
      {"Units Sold", type number},
      {"Manufacturing Price", type number},
      {"Sale Price", type number},
      {"Gross Sales", Currency.Type},
      {"Discounts", Currency.Type},
      {"Sales", Currency.Type},
      {"COGS", Currency.Type},
      {"Profit", Currency.Type},
      {"Date", type datetime},
      {"Month Number", Int64.Type},
      {"Month Name", type text},
      {"Year", Int64.Type}
      })
    in
      ConvertedTypes
in
  __convert_types_2
```

	measure 'Total Units Sold' = ```
SUM ( Financials[Units Sold] )
```
		lineageTag: e38d9d37-82c2-47ca-a242-b926401f28be
		formatString: #,0.00

	measure 'Total Sales' = ```
SUM ( Financials[Sales] )
```
		lineageTag: 5420c5dd-b806-4473-ad67-871ea3184097
		formatString: $#,0

	measure 'Total Profit' = ```
SUM ( Financials[Profit] )
```
		lineageTag: 47d2ac1e-ded6-4863-9e97-49e95bcf520f
		formatString: $#,0

	measure 'Total COGS' = ```
SUM ( Financials[COGS] )
```
		lineageTag: c4a99251-c47c-4417-8b50-c23280a58991
		formatString: $#,0

