# yaml2pbip Sources Configuration Example
# This file defines data source connections for your semantic model

version: 1

sources:
  # Main Snowflake data warehouse connection
  snowflake:
    kind: snowflake
    server: ghoshse-lm85309.snowflakecomputing.com
    warehouse: ANALYTICS_WH
    options:
      # Snowflake connector implementation version
      implementation: "2.0"
      # Custom query tag for tracking queries
      queryTag: yaml2pbip