
table 'Financials'
	lineageTag: f90edbf3-fffe-4683-8604-a0df784f15f0

	column 'Segment'
		dataType: string
		lineageTag: a99a7d48-5a0a-4699-ae09-94b2b1e98f64
		summarizeBy: none
		sourceColumn: Segment

	column 'Country'
		dataType: string
		lineageTag: 46e026e5-5c1c-463d-8c8c-3a47f5808271
		summarizeBy: none
		sourceColumn: Country

	column 'Product'
		dataType: string
		lineageTag: 36016a3b-4030-44e0-b83c-a809ca53ccec
		summarizeBy: none
		sourceColumn: Product

	column 'Discount Band'
		dataType: string
		lineageTag: e10792f4-224d-438c-89dc-e9f585b42b34
		summarizeBy: none
		sourceColumn: Discount Band

	column 'Units Sold'
		dataType: decimal
		lineageTag: 8a2b8267-7ed0-4982-868e-824c4a862f8e
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: Units Sold

	column 'Manufacturing Price'
		dataType: decimal
		lineageTag: 53d2ee84-7720-45a5-8f1e-1ae515dfc546
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Manufacturing Price

	column 'Sale Price'
		dataType: decimal
		lineageTag: dc5f3bf4-4ef2-41be-937f-7cac49548b34
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Sale Price

	column 'Gross Sales'
		dataType: decimal
		lineageTag: 26c612f6-0ded-479e-8d4f-952eff96b75f
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Gross Sales

	column 'Discounts'
		dataType: decimal
		lineageTag: 8704596e-e741-4f41-80af-a304c02a60a4
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Discounts

	column 'Sales'
		dataType: decimal
		lineageTag: cdf82c9b-c446-40db-8409-cdff27cd772c
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Sales

	column 'COGS'
		dataType: decimal
		lineageTag: b6bac3dd-bb33-4650-8e0a-6f76b3b1e313
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: COGS

	column 'Profit'
		dataType: decimal
		lineageTag: 8b831d33-78aa-4d5e-85df-bd1528b81edb
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Profit

	column 'Date'
		dataType: dateTime
		lineageTag: 687bb50e-174f-4309-80e4-09d863c7ea2d
		summarizeBy: none
		sourceColumn: Date

	column 'Month Number'
		dataType: int64
		lineageTag: 4077db50-6dbd-40db-bd9b-99bd99e4c081
		summarizeBy: sum
		sourceColumn: Month Number

	column 'Month Name'
		dataType: string
		lineageTag: 31ea2131-dbf1-42d3-8587-46050c1f04f4
		summarizeBy: none
		sourceColumn: Month Name

	column 'Year'
		dataType: int64
		lineageTag: 5160bb35-84c3-4761-8086-f3ed4c65c88d
		summarizeBy: sum
		sourceColumn: Year

	partition FinancialData = m
		mode: import
		source = ```
let
  Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.148.1226.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
  Sheet = Source{[Item="Financial Sample",Kind="Sheet"]}[Data],
  Selected = Table.SelectColumns(Sheet, {"Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", "Sales", "COGS", "Profit", "Date", "Month Number", "Month Name", "Year"}, MissingField.UseNull),
  Typed = Table.TransformColumnTypes(Selected, {{"Segment", Text.Type}, {"Country", Text.Type}, {"Product", Text.Type}, {"Discount Band", Text.Type}, {"Units Sold", Number.Type}, {"Manufacturing Price", Number.Type}, {"Sale Price", Number.Type}, {"Gross Sales", Number.Type}, {"Discounts", Number.Type}, {"Sales", Number.Type}, {"COGS", Number.Type}, {"Profit", Number.Type}, {"Date", DateTime.Type}, {"Month Number", Int64.Type}, {"Month Name", Text.Type}, {"Year", Int64.Type}}),
  PromotedHeaders = Table.PromoteHeaders(Typed, [PromoteAllScalars=true]),
  CleanedColumns = Table.TransformColumnNames(PromotedHeaders, Text.Trim),
  ConvertedTypes = Table.TransformColumnTypes(CleanedColumns, {
        {"Segment", type text},
        {"Country", type text},
        {"Product", type text},
        {"Discount Band", type text},
        {"Units Sold", type number},
        {"Manufacturing Price", type number},
        {"Sale Price", type number},
        {"Gross Sales", Currency.Type},
        {"Discounts", Currency.Type},
        {"Sales", Currency.Type},
        {"COGS", Currency.Type},
        {"Profit", Currency.Type},
        {"Date", type datetime},
        {"Month Number", Int64.Type},
        {"Month Name", type text},
        {"Year", Int64.Type}
    })
in
  ConvertedTypes
```

	measure 'Total Units Sold' = ```
SUM ( Financials[Units Sold] )
```
		lineageTag: a4eb671b-b2c0-4c51-ba10-68e992cc05d1
		formatString: #,0.00

	measure 'Total Sales' = ```
SUM ( Financials[Sales] )
```
		lineageTag: 85c8877c-ee07-467e-838b-e4c729ede2d9
		formatString: $#,0

	measure 'Total Profit' = ```
SUM ( Financials[Profit] )
```
		lineageTag: 33909a13-5cde-4466-a2dd-f6a1fd63d9cd
		formatString: $#,0

	measure 'Total COGS' = ```
SUM ( Financials[COGS] )
```
		lineageTag: 92ff296e-3a40-439f-acfe-ecc4171e6b61
		formatString: $#,0

