
table 'Key Metrics'
	lineageTag: f945f964-3a6c-4db4-9f27-60b510512f93

	partition 'Key Metrics' = m
		mode: import
		source =
			let
				Source = #table(type table[], {})
			in
				Source

	measure 'Profit Margin %' = ```
DIVIDE (
  [Total Profit],
  [Total Sales],
  0
) * 100

```
		lineageTag: a07124a9-310a-4cba-a685-84079daa8051
		formatString: 0.00%

	measure 'Average Sale Price' = ```
DIVIDE (
  [Total Sales],
  [Total Units Sold],
  0
)

```
		lineageTag: 7f5abd39-4b10-444b-8d1f-b4815561ae67
		formatString: $#,0.00

	measure 'Discount %' = ```
VAR TotalDiscounts = SUM ( Financials[Discounts] )
VAR TotalGrossSales = SUM ( Financials[Gross Sales] )
RETURN
  DIVIDE (
    TotalDiscounts,
    TotalGrossSales,
    0
  ) * 100

```
		lineageTag: 23ec167f-00a0-4c19-b6cd-3cbedd6eec2f
		formatString: 0.00%

	measure 'YTD Sales' = ```
TOTALYTD (
  [Total Sales],
  Financials[Date]
)

```
		lineageTag: 5bb31813-8bf3-4f1f-b726-52b824859afe
		formatString: $#,0

	measure 'YTD Profit' = ```
TOTALYTD (
  [Total Profit],
  Financials[Date]
)

```
		lineageTag: 1903f71f-78a1-4dce-951c-6dee6784ee04
		formatString: $#,0

